{% set name = "rosdistro" %}
{% set version = "0.9.1" %}
{% set sha256 = "b49d9c3c65cc1dff3b56ba61559d70439597417491e1525e4e314f15503517f9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/ros-infrastructure/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - rosdistro_build_cache = rosdistro.cli.rosdistro_build_cache:main
    - rosdistro_freeze_source = rosdistro.cli.rosdistro_freeze_source:main
    - rosdistro_migrate_to_rep_141 = rosdistro.cli.rosdistro_migrate_to_rep_141:main
    - rosdistro_migrate_to_rep_143 = rosdistro.cli.rosdistro_migrate_to_rep_143:main
    - rosdistro_reformat = rosdistro.cli.rosdistro_reformat:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - setuptools
    - pyyaml
    - catkin_pkg
    - rospkg

test:
  commands:
    - rosdistro_build_cache --help
    - rosdistro_freeze_source --help
    - rosdistro_migrate_to_rep_141 --help
    - rosdistro_migrate_to_rep_143 --help
    - rosdistro_reformat --help
  imports:
    - rosdistro
  requires:
    - python {{ python_min }}
    - pip

about:
  home: http://wiki.ros.org/rosdistro
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Tools to work with catkinized rosdistro files
  dev_url: https://github.com/ros-infrastructure/rosdistro

extra:
  recipe-maintainers:
    - wolfv
    - seanyen
    - traversaro
  
