travis:
  secure:
    BINSTAR_TOKEN: NaMLSxO37xwX5LJmJBzG7361TtWn5lrOarbeqQ6+FDofmHdWjoyVRN80kkQysA0pwu1/sZQw0b8CXOXMaDOEJ7GYxxZ0bBP0Mfhq9QqSYtOb6oJ6HzTER1PUCgdZexbF/KtaTQCfZnNwxiluLqvjM5+ON7UseZnuL5H1hE0IPLCJDnbtvP7dHuQVdTfU86SKLuabwWexSDJtgAw660uaV3wVOw33FB1UCyw7YQtYlylua7UniZH88VG9B/BN3muo4Ynh7wIOn3b5BDX31fj/fNRWJemydxIYqMXPgd4Hwyqo1IxsEwHqL8p26KwNb/Q2mIS5vqqQM+Wf+4ZMQx/uidYxcVAshXZ7yfgvm/zdguYE8tcyGjFVxOGnoPISOgoUTz8sT6SPadKk75jkepq4mO7ApymUlVknwrqvvtUfYu+7KY4QX8ZRm1vz9nR7nD1AUIxbDyJ0eeAfx/Psvm4y/qp83ftdUgrvF/Y6WE19r+iZp8Hu1KTN9i7pC4vpqSSs7lmZn1LkWvulXMX8PBPWjPRXKX77FSZ5hJmVhhfIZJBN6Lg2IC9CsYWvD0I1tjLY9Y3EYsu/cJ4d0cwcXbwbSf6StF6+yTiP1OcMywbgj7LshXbehdKV0WwxUuIz6y2wuRNDhawvzsEWHb4jBMhH5TOHAFuIH/E7RlOrOgW3Y0k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: false
